# This docker-compose file construct all the services required
# for Message Oriented Middleware (Rabbit MQ) in a Store Service
version: '3.1'
services:
  web:
    depends_on: 
      - api
    build: ./web
    environment: 
      - NUXT_PORT=5000
      - NUXT_HOST=0.0.0.0
    ports:
     - 9201:5000
  # ASP.NET Core 2.2 REST API: Api[:9200]
  api:
    depends_on: 
      - mssql
      - rabbitmq
    build: ./api/DistributedSystems.Orders.Api
    ports:
      - 9200:80
  # MS SQL Server 2017
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Prueba2019
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes: 
      - ./data/mssql:/var/opt/mssql
  # Rabbit MQ
  rabbitmq:
    image: "rabbitmq:3-management"
    environment: 
      - RABBITMQ_ERLANG_COOKIE="SWQOKODSQALRPCLNMEQG"
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
 