#AMQP RabbitMQ configuration 
server:
  port: ${PORT:8081}
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATABASE_URL:jdbc:sqlserver://localhost;databaseName=Store}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:Prueba2019}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  rabbitmq: 
    host: ${RABBITMQ_HOSTNAME:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    listener:
      simple: 
        concurrency: 4
        max-concurrency: 8  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:alertador.pruebas@gmail.com}
    password: ${MAIL_PASSWORD:xnxtfmuidfolhitn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
queue:
  orders:
    name: orders
    exchange: ""
  warehouse:
    name: warehouse
    exchange: ""
