version: '3.1'
services:
  ordersapi:
    container_name: ordersapi
    depends_on: 
      - mssql
      - rabbitmq
    build: ./DistributedSystems.Orders.Api
    ports:
      - "9200:80"
  mssql:
    container_name: mssql
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Prueba2019
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes: 
      - ./data/mssql:/var/opt/mssql
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
 